### ISSUE TITLE
Colors placed in variables.less doesn't apply

### ISSUE THREAD

**Issue by JonneBR** [elvisduru/next-antd-example#1]
Hey man, thanks for the article and the repo. I've followed the setup in the article and even cloned your repo, but the colors placed in ./styles/variables.less does't apply, they only work if I place them in next.config.js in modifyVars.

**Comment by elvisduru** [comment]
Hi @JonneBR , to use the variables.less file, you'll have to include it in the _app.js file using require(). Also make sure the antd default styles are removed from _app.js, as the variable.less file already imports it.
![image](https://user-images.githubusercontent.com/28690701/160926790-86badc8b-680f-460f-b5f8-68aa17f553f9.png)

**Comment by elvisduru** [comment]
@JonneBR , let me know if that works for you bro.

**Comment by elvisduru** [comment]
I've also updated the repo with the changes I mentioned earlier.

**Comment by JonneBR** [comment]
> @JonneBR , let me know if that works for you bro.

I cloned your repo with the updates and it is still not working :(

**Comment by JonneBR** [comment]
> @JonneBR , let me know if that works for you bro.

It worked now, thanks man, great job! 👍
